<?php

/**
 * @file guardian_news.module
 *
 * Implements an AngularJS-driven block.
 */

/**
 * Implements hook_block_info().
 */
function guardian_news_block_info() {
  $blocks['guardian_latest_block'] = array(
    'info' => t('Latest articles from guardian'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function guardian_news_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'guardian_latest_block':
      $path = drupal_get_path('module', 'guardian_news');
      drupal_add_js(array('guardian_latest_news' => array('url' => 'http://content.guardianapis.com/search')), 'setting');
      drupal_add_js(array('guardian_latest_news' => array('apiKey' => 'hfqncwz9hxwstua2f8qszjj8')), 'setting');
      drupal_add_js(array('guardian_latest_news' => array('pageSize' => 3)), 'setting');
      drupal_add_js(array('guardian_latest_news' => array('orderBy' => 'newest')), 'setting');

      $block['subject'] = t('Articles from guardian');
      $block['content'] = array(
        '#theme' => 'guardian_latest_news',
        '#attached' => array(
          'js' => array(
            'https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js',
            $path . '/guardian_latest_news.js',
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function guardian_news_theme() {
  return array(
    'guardian_latest_news' => array(
      'template' => 'guardian_news',
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function guardian_news_menu() {
  $items['admin/structure/guardian_news'] = array(
    'title' => 'The Guardian news',
    'type' => MENU_NORMAL_ITEM,
    'description' => 'Admin page for module guardian_news.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_guardian_news_admin_form'),
    'access arguments' => array('administer content'),
  );

  return $items;
}

/**
 * Admin page for module
 */
function _guardian_news_admin_form($form, &$form_state) {

  $form['title'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Settings for the Guardian news block.</p>',
  );

  $form['post_number'] = array(
    '#type' => 'select',
    '#title' => t('Number of articles to be displayed'),
    '#options' => array(
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
    ),
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Save changes'),
  );

  return $form;
}