<?php

/**
 * @file guardian_news.module
 *
 * Implements an AngularJS-driven block.
 */

/**
 * Implements hook_block_info().
 */
function guardian_news_block_info() {
  $blocks['guardian_latest_block'] = array(
    'info' => t('Latest articles from guardian'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function guardian_news_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'guardian_latest_block':
      $path = drupal_get_path('module', 'guardian_news');
      drupal_add_js(array('guardian_latest_news' => array('url' => 'http://content.guardianapis.com/search')), 'setting');
      drupal_add_js(array('guardian_latest_news' => array('apiKey' => 'hfqncwz9hxwstua2f8qszjj8')), 'setting');
      drupal_add_js(array('guardian_latest_news' => array('pageSize' => 3)), 'setting');
      drupal_add_js(array('guardian_latest_news' => array('orderBy' => 'newest')), 'setting');

      $block['subject'] = t('Articles from guardian');
      $block['content'] = array(
        '#theme' => 'guardian_latest_news',
        '#attached' => array(
          'js' => array(
            'https://ajax.googleapis.com/ajax/libs/angularjs/1.0.7/angular.min.js',
            $path . '/guardian_latest_news.js',
          ),
        ),
      );
      break;
  }
  return $block;
}

/**
 * Implements hook_theme().
 */
function guardian_news_theme() {
  return array(
    'guardian_latest_news' => array(
      'template' => 'guardian_news',
      'variables' => array(),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function guardian_news_menu() {
  $items['admin/structure/guardian_news'] = array(
    'title' => 'The Guardian news',
    'type' => MENU_NORMAL_ITEM,
    'description' => 'Admin page for module guardian_news.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_guardian_news_admin_form'),
    'access arguments' => array('administer content'),
  );

  return $items;
}

/**
 * Admin page for module.
 */
function _guardian_news_admin_form($form, &$form_state) {

  $form['title'] = array(
    '#type' => 'markup',
    '#markup' => '<p>Settings for the Guardian news block.</p>',
  );

  $sections = guardianapi_get_sections_all();
  foreach ($sections as $key => $section) {
    $sections[$section['id']] = $section['webTitle'];
    unset($sections[$key]);
  }
  ksort($sections);
  $form['sections'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Sections to be displayed'),
    '#options' => $sections,
  );

  $form['tags'] = array(
    '#type' => 'autocomplete',
    '#title' => t('Filter by tags'),
    '#options' => $sections,
  );

  $form['post_number'] = array(
    '#type' => 'select',
    '#title' => t('Number of articles to be displayed (maximum)'),
    '#options' => array(
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
    ),
  );

  $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Save changes'),
  );

  return $form;
}

/**
 * Admin page submit function.
 */
function _guardian_news_admin_form_submit($form, &$form_state) {


}

/**
 * Returns all the article sections.
 */
function guardianapi_get_sections_all() {
  $sections = guardianapi_query('sections');
  if (!empty($sections)) {
    return $sections;
  }

  return FALSE;
}

/**
 * Function that performs a query in Guardian's API.
 */
function guardianapi_query($apicom, $api_key = 'test', $options = array()) {
  if (!in_array($apicom, array('search', 'tags', 'sections'))) {
    return FALSE;
  }

  $url = sprintf('http://content.guardianapis.com/%s?api-key=%s', $apicom, $api_key);

  $response_json = file_get_contents($url);

  if ($response_json) {
    $response = json_decode($response_json, TRUE);
    if (!empty($response['response']['results'])) {
      return $response['response']['results'];
    }
  }

  return FALSE;
}